title: "Tuğcan ÖNBAŞ"
email: tgcn@tugcanonbas.com
description: "Multidisciplinary Designer & Software Developer based in Ingolstadt, Germany."
baseurl: "/uxdm_vcux-hackathon-tugcanonbas"
url: "https://tugcanonbas.github.io"
author:
  name: "Tuğcan ÖNBAŞ"
  twitter: "tgcn_dev"
  email: "tgcn@tugcanonbas.com"
  
markdown: kramdown
theme: null

collections:
  projects:
    output: true
    permalink: /projects/:slug/
  publications:
    output: true
    permalink: /publications/:slug/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/tugcanonbas.jpg # Default social image
